services:
  db:
    image: postgres:16
    container_name: shortener-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortener-db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: shortener-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  db_data:
